name: Dist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: opeik/electroncg
          submodules: true

      - name: Build runback
        run: cd bundles/runback && npm install && npm run-script build
        
      - name: Build electroncg
        run: npm install -g electron-builder && npm install && yarn dist
