name: Dist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Runback
        uses: actions/checkout@v1

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install && git submodule update --init --recursive && cd lib/nodecg && npm install
 
      - if: matrix.os == 'ubuntu-latest'
        name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic 

      - name: Build runback
        run: npm run-script build

      - name: Create and publish binary
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.ELECTRON_BUILDER_PAT }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: release
        env:
          USE_HARD_LINKS: false
