name: Dist

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Runback
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install runback dependencies
        run: npm install

      - name: Install nodecg dependencies
        working-directory: lib/nodecg
        run: npm install

      - name: Install nodecg build dependencies
        working-directory: build/nodecg
        run: npm install

      - name: Install runback build dependencies
        working-directory: build/nodecg/bundles/runback
        run: npm install

      - name: Build runback
        run: npm run-script build

      - name: Create and publish binary
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.ELECTRON_BUILDER_PAT }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: release
        env:
          USE_HARD_LINKS: false
