name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out runback
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: "{,lib/nodecg}/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yark.lock') }}

      - name: Install runback dependencies
        run: yarn install

      - name: Install nodecg dependencies
        run: yarn install
        working-directory: lib/nodecg

      - name: Build runback
        run: yarn build

      - name: Prepare electron build
        run: bash ./electron-builder/prepare-build.sh

      - name: Build electron
        run: yarn release
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.ELECTRON_BUILDER_PAT }}
