name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            USE_HARD_LINKS: false

          - os: ubuntu-latest
            USE_HARD_LINKS: false

          - os: windows-latest
            USE_HARD_LINKS: true

    steps:
      - name: Check out Runback
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Cache packages
        if: matrix.os != 'windows-latest'
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Clear npm cache on Windows
        if: matrix.os == 'windows-latest'
        run: npm cache clean --force

      - name: Install runback dependencies
        run: yarn install

      - name: Install nodecg dependencies
        working-directory: lib/nodecg
        run: yarn install

      - name: Install nodecg build dependencies
        working-directory: build/nodecg
        run: yarn install

      - name: Install runback build dependencies
        working-directory: build/nodecg/bundles/runback
        run: yarn install

      - name: Build runback
        run: yarn build

      - name: Create and publish binary
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          github_token: ${{ secrets.ELECTRON_BUILDER_PAT }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          build_script_name: release
        env:
          USE_HARD_LINKS: ${{matrix.USE_HARD_LINKS}}
