name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out runback-electron
        uses: actions/checkout@v2
        with:
          repository: opeik/runback-electron
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Check out nodecg
        uses: actions/checkout@v2
        with:
          repository: nodecg/nodecg
          path: lib/nodecg
          ref: legacy-1.x
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Check out runback
        uses: actions/checkout@v2
        with:
          repository: opeik/runback
          path: lib/nodecg/bundles/runback
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: "{,lib/nodecg,lib/nodecg/bundles/runback}/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yark.lock') }}

      - name: Install runback-electron dependencies
        run: yarn install

      - name: Install nodecg dependencies
        run: npm install --production
        working-directory: lib/nodecg

      - name: Install runback dependencies
        run: yarn install
        working-directory: lib/nodecg/bundles/runback

      - name: Install json
        run: sudo npm install -g json

      - name: Set package version
        run:
          VERSION=$(json "version" -f lib/nodecg/bundles/runback/package.json) && \
          json -I -f package.json -e "this.version=\"$VERSION\""
        shell: bash

      - name: Build runback
        run: yarn build
        working-directory: lib/nodecg/bundles/runback

      - name: Build electron app
        run: yarn dist
        env:
          USE_HARD_LINKS: false
          GH_TOKEN: ${{ secrets.PAT }}
